import type { StaticImageData } from "next/image";
import filmsLogo from "../../LOGO X NODOS/FILMS/png/LTT_FILMS_LOGO_1920_FX.png";

export type BlogNodeId = "films" | "studio" | "sound" | "design" | "agency" | "time";

export type BlogNode = {
  id: BlogNodeId;
  name: string;
  index: string;
  logo: string | StaticImageData;
  territory: string;
};

export type BlogPost = {
  slug: string;
  title: string;
  dek: string;
  node: BlogNodeId;
  category: string;
  date: string;
  displayDate: string;
  readingTime: string;
  author: string;
  image: string;
  imagePosition?: string;
  alt: string;
  imageCredit: string;
  priority: "lead" | "wide" | "portrait" | "standard";
  keywords: string[];
};

export const blogNodes: BlogNode[] = [
  {
    id: "films",
    name: "Films",
    index: "01",
    logo: filmsLogo,
    territory: "Cinematografía",
  },
  {
    id: "studio",
    name: "Studio",
    index: "02",
    logo: "/assets/logos/LTT_STUDIO_LOGO_1920_FX.png",
    territory: "Técnica, equipo y procesos",
  },
  {
    id: "sound",
    name: "Sound",
    index: "03",
    logo: "/assets/logos/LTT_SOUND_LOGO_1920_FX.png",
    territory: "Escucha, vibración y materia",
  },
  {
    id: "design",
    name: "Design",
    index: "04",
    logo: "/assets/logos/LTT_DESIGN_LOGO_1920_FX.png",
    territory: "Forma, función y lenguaje visual",
  },
  {
    id: "agency",
    name: "Agency",
    index: "05",
    logo: "/assets/logos/LTT_AGENCY_LOGO_1920_FX.png",
    territory: "Estrategia, marca y comunicación",
  },
  {
    id: "time",
    name: "Time",
    index: "06",
    logo: "/assets/logos/LTT_TIME_LOGO_1920_FX.png",
    territory: "Memoria, oficio y cultura",
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: "como-preparar-un-scouting-de-locacion-cinematografica",
    title: "Cómo preparar un scouting de locación cinematográfica",
    dek: "Una visita útil no sólo confirma que el lugar se ve bien: descubre qué permite filmar, qué exige resolver y qué relato ya contiene.",
    node: "films",
    category: "Producción",
    date: "2026-09-24",
    displayDate: "24.09.26",
    readingTime: "8 min",
    author: "LATTICCE Films",
    image: "/assets/images/blog/generated/films-location-scout-v1.jpg",
    imagePosition: "center 50%",
    alt: "Profesional revisa un plano durante el scouting de una arquitectura de concreto con vista a la ciudad.",
    imageCredit: "Dirección visual LATTICCE · Scouting de locación",
    priority: "lead",
    keywords: ["scouting", "locación", "producción", "rodaje", "cine", "preproducción"],
  },
  {
    slug: "como-dirigir-a-una-persona-que-no-es-modelo",
    title: "Cómo dirigir a una persona que no es modelo",
    dek: "La dirección más honesta no pide que alguien actúe como otra persona: construye una situación en la que pueda estar presente.",
    node: "studio",
    category: "Producción",
    date: "2026-09-26",
    displayDate: "26.09.26",
    readingTime: "7 min",
    author: "LATTICCE Studio",
    image: "/assets/images/blog/generated/studio-directing-nonmodel-v1.jpg",
    imagePosition: "center 48%",
    alt: "Ceramista trabaja una pieza en su taller iluminado por una ventana durante una sesión documental.",
    imageCredit: "Dirección visual LATTICCE · Retrato en proceso",
    priority: "portrait",
    keywords: ["dirección", "retrato", "personas", "fotografía", "producción", "documental"],
  },
  {
    slug: "como-grabar-una-entrevista-en-una-locacion-dificil",
    title: "Cómo grabar una entrevista en una locación difícil",
    dek: "No siempre podemos silenciar el mundo. La clave es identificar qué ruido pertenece al lugar, qué fuente proteger y qué solución cabe en la escena.",
    node: "sound",
    category: "Grabación",
    date: "2026-09-29",
    displayDate: "29.09.26",
    readingTime: "8 min",
    author: "LATTICCE Sound",
    image: "/assets/images/blog/generated/sound-location-interview-v1.jpg",
    imagePosition: "center 48%",
    alt: "Entrevistadora conversa con un chef en una cocina activa mientras un técnico controla el sonido directo.",
    imageCredit: "Dirección visual LATTICCE · Entrevista en locación",
    priority: "standard",
    keywords: ["entrevista", "sonido directo", "locación", "micrófonos", "acústica", "grabación"],
  },
  {
    slug: "conocias-esta-tecnica-risografia",
    title: "¿Conocías esta técnica? Risografía",
    dek: "La risografía deja que la tinta, el registro y el papel participen en la imagen: una técnica de edición que convierte pequeñas variaciones en lenguaje.",
    node: "design",
    category: "Recursos",
    date: "2026-10-01",
    displayDate: "01.10.26",
    readingTime: "7 min",
    author: "LATTICCE Design",
    image: "/assets/images/blog/generated/design-risograph-v1.jpg",
    imagePosition: "center 50%",
    alt: "Diseñadora ajusta una impresión a dos tintas frente a una máquina de risografía en un taller independiente.",
    imageCredit: "Dirección visual LATTICCE · Taller de risografía",
    priority: "wide",
    keywords: ["risografía", "impresión", "tinta", "registro", "papel", "diseño editorial"],
  },
  {
    slug: "la-pagina-de-inicio-no-tiene-que-contarlo-todo",
    title: "La página de inicio no tiene que contarlo todo",
    dek: "Una buena página de inicio no es un inventario. Es un umbral: orienta, propone una siguiente acción y deja espacio para que el resto del sitio haga su trabajo.",
    node: "agency",
    category: "Estrategia",
    date: "2026-10-03",
    displayDate: "03.10.26",
    readingTime: "8 min",
    author: "LATTICCE Agency",
    image: "/assets/images/blog/generated/agency-homepage-architecture-v1.jpg",
    imagePosition: "center 50%",
    alt: "Persona recorre una arquitectura de concreto y aluminio con información visual integrada en sus muros.",
    imageCredit: "Dirección visual LATTICCE · Arquitectura de navegación",
    priority: "standard",
    keywords: ["homepage", "sitio web", "navegación", "estrategia", "contenido", "conversión"],
  },
  {
    slug: "cinco-fotografos-de-boda-mexicanos",
    title: "Cinco fotógrafos de boda mexicanos que vale la pena conocer",
    dek: "Una selección editorial de miradas documentales y de destino para estudiar antes de decidir cómo quieres que una celebración permanezca en el tiempo.",
    node: "time",
    category: "Referencias",
    date: "2026-10-06",
    displayDate: "06.10.26",
    readingTime: "9 min",
    author: "LATTICCE Time",
    image: "/assets/images/blog/generated/time-wedding-photographers-v1.jpg",
    imagePosition: "center 50%",
    alt: "Hojas de contacto y negativos de celebraciones de destino en México sobre una mesa editorial color marfil.",
    imageCredit: "Dirección visual LATTICCE · Archivo editorial de celebración",
    priority: "wide",
    keywords: ["fotografía de boda", "México", "fotógrafos", "archivo", "celebración", "referencias"],
  },
  {
    slug: "el-espacio-tambien-dirige",
    title: "El espacio también dirige",
    dek: "Leer profundidad, escala y vacío antes de mover la cámara cambia por completo la puesta en escena.",
    node: "films",
    category: "Narrativa visual",
    date: "2026-09-21",
    displayDate: "21.09.26",
    readingTime: "8 min",
    author: "LATTICCE Films",
    image: "/assets/images/blog/generated/films-space-directs-v1.jpg",
    imagePosition: "center 50%",
    alt: "Explorador de locaciones observa la entrada de luz en una arquitectura monumental de concreto.",
    imageCredit: "Dirección visual LATTICCE · Estudio de espacio cinematográfico",
    priority: "lead",
    keywords: ["cine", "espacio", "puesta en escena", "narrativa", "composición"],
  },
  {
    slug: "exponer-para-la-luz-que-cambia",
    title: "Exponer para la luz que cambia",
    dek: "Un método de cobertura para conservar piel, atmósfera y gesto cuando la escena nunca permanece quieta.",
    node: "studio",
    category: "Tips técnicos",
    date: "2026-09-18",
    displayDate: "18.09.26",
    readingTime: "7 min",
    author: "LATTICCE Studio",
    image: "/assets/images/book/diana-meril/diana-meril-hero.jpg",
    imagePosition: "center 42%",
    alt: "Diana Meril canta entre luz ámbar y reflejos durante su concierto en Foro La Paz.",
    imageCredit: "Diana Meril, Ámbar · Foto: Hernán Jiménez Herrera",
    priority: "portrait",
    keywords: ["exposición", "concierto", "fotografía", "contraste", "luz"],
  },
  {
    slug: "la-mezcla-empieza-en-la-distancia",
    title: "La mezcla empieza en la distancia",
    dek: "Antes del procesamiento están la fuente, el aire y la posición desde la que decidimos escuchar.",
    node: "sound",
    category: "Grabación",
    date: "2026-09-15",
    displayDate: "15.09.26",
    readingTime: "7 min",
    author: "LATTICCE Sound",
    image: "/assets/images/book/surfistas/surfistas-hero.jpg",
    imagePosition: "center 48%",
    alt: "Saxofonista y guitarrista de Surfistas del Sistema tocan espalda con espalda.",
    imageCredit: "Surfistas del Sistema · Foto: Hernán Jiménez Herrera",
    priority: "standard",
    keywords: ["sonido", "distancia", "grabación", "micrófonos", "escucha"],
  },
  {
    slug: "el-color-como-sistema-de-orientacion",
    title: "El color como sistema de orientación",
    dek: "Cuando el color organiza jerarquías y transiciones deja de ser acabado para convertirse en estructura.",
    node: "design",
    category: "Diseño gráfico",
    date: "2026-09-11",
    displayDate: "11.09.26",
    readingTime: "6 min",
    author: "LATTICCE Design",
    image: "/assets/images/blog/generated/design-color-system-v1.jpg",
    imagePosition: "center 42%",
    alt: "Diseñador combina acrílicos translúcidos, muestras de tinta y papeles de color sobre una mesa.",
    imageCredit: "Dirección visual LATTICCE · Estudio de color y materia",
    priority: "wide",
    keywords: ["color", "jerarquía", "sistema", "identidad", "diseño"],
  },
  {
    slug: "la-atencion-no-se-compra-se-construye",
    title: "La atención no se compra. Se construye.",
    dek: "Una audiencia permanece cuando cada contacto confirma una expectativa clara y valiosa.",
    node: "agency",
    category: "Estrategia",
    date: "2026-09-08",
    displayDate: "08.09.26",
    readingTime: "8 min",
    author: "LATTICCE Agency",
    image: "/assets/images/blog/generated/agency-attention-v1.jpg",
    imagePosition: "center 58%",
    alt: "Visitantes recorren una instalación inmersiva construida con agua, cristal y proyecciones.",
    imageCredit: "Dirección visual LATTICCE · Experiencia de atención inmersiva",
    priority: "standard",
    keywords: ["atención", "audiencia", "estrategia", "marca", "comunidad"],
  },
  {
    slug: "una-noche-no-cabe-en-una-imagen",
    title: "Una noche no cabe en una imagen",
    dek: "La memoria editorial aparece en la secuencia: apertura, proximidad, pausa y regreso.",
    node: "time",
    category: "Archivo",
    date: "2026-09-04",
    displayDate: "04.09.26",
    readingTime: "6 min",
    author: "LATTICCE Time",
    image: "/assets/images/blog/generated/time-one-night-v1.jpg",
    imagePosition: "center 38%",
    alt: "Editora organiza fotografías, contactos y un álbum de lino sobre una mesa color marfil.",
    imageCredit: "Dirección visual LATTICCE · Memoria editorial física",
    priority: "wide",
    keywords: ["memoria", "fotografía", "secuencia", "archivo", "edición"],
  },
  {
    slug: "poner-en-escena-es-construir-relaciones",
    title: "Poner en escena es construir relaciones",
    dek: "Cuerpo, arquitectura, luz y duración funcionan cuando comparten una misma tensión dramática.",
    node: "films",
    category: "Dirección",
    date: "2026-08-30",
    displayDate: "30.08.26",
    readingTime: "9 min",
    author: "LATTICCE Films",
    image: "/assets/images/blog/generated/films-blocking-scene-v1.jpg",
    imagePosition: "center 42%",
    alt: "Director construye la distancia entre dos intérpretes dentro de un pasaje brutalista.",
    imageCredit: "Dirección visual LATTICCE · Ensayo de puesta en escena",
    priority: "portrait",
    keywords: ["dirección", "cuerpo", "puesta en escena", "cine", "arquitectura"],
  },
  {
    slug: "cubrir-un-concierto-sin-borrar-al-publico",
    title: "Cubrir un concierto sin borrar al público",
    dek: "La audiencia no es fondo: es escala, respuesta y contrapunto dentro del relato visual.",
    node: "studio",
    category: "Producción",
    date: "2026-08-26",
    displayDate: "26.08.26",
    readingTime: "7 min",
    author: "LATTICCE Studio",
    image: "/assets/images/book/diana-meril/diana-meril-gallery-08.jpg",
    imagePosition: "center 46%",
    alt: "Diana Meril aparece en silueta mientras el público sostiene teléfonos y luces.",
    imageCredit: "Diana Meril, Ámbar · Foto: Hernán Jiménez Herrera",
    priority: "standard",
    keywords: ["producción", "cobertura", "público", "concierto", "fotografía"],
  },
  {
    slug: "lo-que-el-publico-devuelve-al-escenario",
    title: "Lo que el público devuelve al escenario",
    dek: "La energía de una sala también se escucha: aparece en coros, pausas, reflejos y cambios de intensidad.",
    node: "sound",
    category: "Diseño sonoro",
    date: "2026-08-21",
    displayDate: "21.08.26",
    readingTime: "6 min",
    author: "LATTICCE Sound",
    image: "/assets/images/book/la-bande/la-bande-gallery-08.jpg",
    imagePosition: "center 36%",
    alt: "La Bande-Son Imaginaire y su público comparten una escena azul en el Pepsi Center WTC.",
    imageCredit: "La Bande-Son Imaginaire · Foto: Hernán Jiménez Herrera",
    priority: "wide",
    keywords: ["audiencia", "ambiente", "sonido directo", "dinámica", "espacio"],
  },
  {
    slug: "disenar-una-secuencia-no-una-coleccion",
    title: "Diseñar una secuencia, no una colección",
    dek: "Editar imágenes es crear ritmo, contraste y continuidad; no sólo reunir las más espectaculares.",
    node: "design",
    category: "Diseño editorial",
    date: "2026-08-16",
    displayDate: "16.08.26",
    readingTime: "6 min",
    author: "LATTICCE Design",
    image: "/assets/images/blog/generated/design-sequence-v1.jpg",
    imagePosition: "center 48%",
    alt: "Editora ordena fotografías y hojas de contacto en el muro de un estudio.",
    imageCredit: "Dirección visual LATTICCE · Mesa de edición fotográfica",
    priority: "standard",
    keywords: ["edición", "secuencia", "ritmo", "fotografía", "diseño editorial"],
  },
  {
    slug: "una-idea-debe-sobrevivir-al-formato",
    title: "Una idea debe sobrevivir al formato",
    dek: "Una campaña es coherente cuando su principio puede cambiar de escala sin perder intención.",
    node: "agency",
    category: "Branding",
    date: "2026-08-10",
    displayDate: "10.08.26",
    readingTime: "8 min",
    author: "LATTICCE Agency",
    image: "/assets/images/blog/generated/agency-formats-v1.jpg",
    imagePosition: "center 46%",
    alt: "Un mismo sistema visual ocupa impresos, objetos y proyecciones dentro de una galería.",
    imageCredit: "Dirección visual LATTICCE · Sistema de campaña multiformato",
    priority: "portrait",
    keywords: ["campaña", "branding", "formatos", "idea", "consistencia"],
  },
  {
    slug: "editar-memoria-es-conservar-relaciones",
    title: "Editar memoria es conservar relaciones",
    dek: "Un archivo permanece vivo cuando guarda contexto y permite que las imágenes vuelvan a dialogar.",
    node: "time",
    category: "Oficio y creatividad",
    date: "2026-08-03",
    displayDate: "03.08.26",
    readingTime: "7 min",
    author: "LATTICCE Time",
    image: "/assets/images/blog/generated/time-archive-v1.jpg",
    imagePosition: "center 42%",
    alt: "Archivista conserva negativos y fotografías dentro de fundas libres de ácido.",
    imageCredit: "Dirección visual LATTICCE · Conservación de archivo fotográfico",
    priority: "wide",
    keywords: ["archivo", "memoria", "metadatos", "fotografía", "edición"],
  },
  {
    slug: "conocias-esta-tecnica-linograbado-reduccion",
    title: "¿Conocías esta técnica de ilustración?",
    dek: "El linograbado por reducción construye varios colores tallando y estampando una misma matriz por etapas.",
    node: "design",
    category: "Recursos",
    date: "2026-09-20",
    displayDate: "20.09.26",
    readingTime: "7 min",
    author: "LATTICCE Design",
    image: "/assets/images/blog/generated/design-linocut-v1.jpg",
    imagePosition: "center 50%",
    alt: "Grabador talla una matriz de linóleo junto a rodillos, tintas y pruebas impresas sobre papel.",
    imageCredit: "Dirección visual LATTICCE · Taller de linograbado por reducción",
    priority: "standard",
    keywords: ["ilustración", "linograbado", "reducción", "grabado", "tinta", "impresión"],
  },
  {
    slug: "conecta-mejor-el-secreto-de-un-buen-ecommerce",
    title: "Conecta mejor: el secreto de un buen ecommerce",
    dek: "La tienda que convierte no empieza en el botón de compra, sino en una promesa clara y una operación que la cumple.",
    node: "agency",
    category: "Marketing digital",
    date: "2026-09-19",
    displayDate: "19.09.26",
    readingTime: "8 min",
    author: "LATTICCE Agency",
    image: "/assets/images/blog/generated/agency-ecommerce-v1.jpg",
    imagePosition: "center 48%",
    alt: "Equipo revisa producto y prepara pedidos dentro de una operación de comercio electrónico.",
    imageCredit: "Dirección visual LATTICCE · Operación de ecommerce",
    priority: "wide",
    keywords: ["ecommerce", "conversión", "audiencia", "producto", "checkout", "experiencia"],
  },
  {
    slug: "antes-de-pedir-presupuesto-audiovisual",
    title: "Antes de pedir un presupuesto audiovisual",
    dek: "Seis decisiones que debes definir para recibir una propuesta comparable, realista y útil para tu producción.",
    node: "films",
    category: "Producción",
    date: "2026-09-17",
    displayDate: "17.09.26",
    readingTime: "8 min",
    author: "LATTICCE Films",
    image: "/assets/images/blog/generated/films-budget-location-v1.jpg",
    imagePosition: "center 48%",
    alt: "Dos productores miden una locación industrial y registran sus condiciones técnicas.",
    imageCredit: "Dirección visual LATTICCE · Diagnóstico de locación",
    priority: "portrait",
    keywords: ["presupuesto", "producción", "brief", "rodaje", "cotización", "alcance"],
  },
  {
    slug: "como-grabar-una-voz",
    title: "Graba una voz que pueda sostener la mezcla",
    dek: "Distancia, patrón polar, ganancia y una interpretación cómoda importan más que acumular procesamiento.",
    node: "sound",
    category: "Tips técnicos",
    date: "2026-09-14",
    displayDate: "14.09.26",
    readingTime: "7 min",
    author: "LATTICCE Sound",
    image: "/assets/images/blog/generated/sound-record-voice-v1.jpg",
    imagePosition: "center 46%",
    alt: "Vocalista graba frente a un micrófono de condensador y un filtro antipop en una cabina tratada.",
    imageCredit: "Dirección visual LATTICCE · Sesión de grabación vocal",
    priority: "standard",
    keywords: ["voz", "grabación", "micrófono", "ganancia", "pop filter", "acústica"],
  },
  {
    slug: "como-editar-un-piano",
    title: "Edita un piano sin quitarle respiración",
    dek: "Cómo limpiar, compilar y ajustar tiempo conservando el ataque, el pedal y la intención de la interpretación.",
    node: "sound",
    category: "Postproducción",
    date: "2026-09-12",
    displayDate: "12.09.26",
    readingTime: "8 min",
    author: "LATTICCE Sound",
    image: "/assets/images/blog/generated/sound-edit-piano-v1.jpg",
    imagePosition: "center 50%",
    alt: "Editor trabaja una toma de piano frente a una consola mientras observa el mecanismo del instrumento.",
    imageCredit: "Dirección visual LATTICCE · Edición de piano",
    priority: "wide",
    keywords: ["piano", "edición", "comping", "pedal", "fase", "postproducción"],
  },
  {
    slug: "cinco-wedding-planners-mexico",
    title: "Cinco wedding planners de México que vale la pena conocer",
    dek: "Una selección editorial para comparar enfoque, región, escala y nivel de producción antes de elegir equipo.",
    node: "time",
    category: "Referencias",
    date: "2026-09-10",
    displayDate: "10.09.26",
    readingTime: "9 min",
    author: "LATTICCE Time",
    image: "/assets/images/blog/generated/time-wedding-planners-v1.jpg",
    imagePosition: "center 50%",
    alt: "Wedding planner revisa planos y circulación durante una visita técnica en una hacienda mexicana.",
    imageCredit: "Dirección visual LATTICCE · Visita técnica de planeación",
    priority: "standard",
    keywords: ["wedding planner", "México", "bodas", "producción", "destino", "proveedores"],
  },
];

export function getBlogNode(id: BlogNodeId) {
  return blogNodes.find((node) => node.id === id)!;
}

export function getBlogPost(slug: string) {
  return blogPosts.find((post) => post.slug === slug);
}
